language: generic
sudo: required
services:
  - docker
script:
  - export VERSION="$TRAVIS_TAG"
  - docker-compose -f docker-compose.ci.build.yml -f docker-compose.yml up --abort-on-container-exit
deploy:
  on:
    tags: true
    all_branches: true
  skip_cleanup: true
  provider: script
  script: docker-compose -f docker-compose.ci.publish.yml up --abort-on-container-exit
