version: '2'

services:
  graylog-mongo:
    image: "mongo:3"
  graylog-elasticsearch:
    image: "elasticsearch:2"
    volumes:
      - ./graylog/data/elasticsearch:/usr/share/elasticsearch/data
    command: "elasticsearch -Des.cluster.name='graylog'"
  graylog-server:
    image: graylog2/server:2.2.3-1
    volumes:
      - ./graylog/data/journal:/usr/share/graylog/data/journal
      - ./graylog/config:/usr/share/graylog/data/config
    environment:
      GRAYLOG_PASSWORD_SECRET: "!ux*lAfQVjaRT8iI"
      GRAYLOG_ROOT_PASSWORD_SHA2: d7fead7a694914252c363044af4ecca69cba6c621bb3f449e3766bbe30e83ae9
      GRAYLOG_WEB_ENDPOINT_URI: http://127.0.0.1:9000/api
    links:
      - graylog-mongo:mongo
      - graylog-elasticsearch:elasticsearch
    ports:
      - "9000:9000"
      - "12201:12201/udp"
      - "1514:1514/udp"
