version: '2'

services:
  ci-build:
    image: microsoft/dotnet:1.1-sdk
    volumes:
      - .:/src
    working_dir: /src
    command: |
      /bin/bash -c '
        versionArg=$$([[ ! -z $VERSION ]] && echo "/p:PackageVersion=$VERSION" || echo "" fi)
        dotnet restore
        dotnet build -c Release $$versionArg
        find test/*/*Tests.csproj | xargs dotnet test -c Release --no-build
      '
